import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

csv_file = 'NLTE_nh3_1e-6_parallel_12rays_v2.csv'

# Read and filter the data
df = pd.read_csv(csv_file, comment="#")

# Filter out rows where the model might have failed (if N_NH3 or numberdensity is NaN)
df = df.dropna(subset=['N_NH3', 'numberdensity'])
df = df[df['T_cloud'] == 36.0]

x = df['numberdensity']
y = df['N_NH3']

def remove_top_outliers(data, percentile=97):
    """Replaces values above the given percentile with NaN."""
    # Ensure we calculate the percentile only on valid numbers
    threshold = np.percentile(data.dropna(), percentile)
    return np.where(data > threshold, np.nan, data)

def plot_scatter_and_contour(x, y, z, title, filename, cmap_name):
    """
    Generates a 1x2 figure with a scatter plot and a contour plot.
    """
    # ---------------------------------------------------------
    # CRITICAL: Contouring functions crash if they encounter NaNs.
    # We must filter out the NaNs generated by outlier removal.
    # ---------------------------------------------------------
    valid_mask = ~np.isnan(z) & ~np.isnan(x) & ~np.isnan(y)
    xv = x[valid_mask]
    yv = y[valid_mask]
    zv = z[valid_mask]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # --- Plot 1: Scatter Map ---
    scatter = ax1.scatter(x, y, c=z, cmap=cmap_name, edgecolor='k')
    fig.colorbar(scatter, ax=ax1, label=title)
    ax1.set_xscale('log')
    ax1.set_yscale('log')
    ax1.set_xlabel('Number Density')
    ax1.set_ylabel('N_NH3')
    ax1.set_title(f'{title} (Scatter Map)')
    ax1.grid(True, which="both", ls="--", alpha=0.5)

    # --- Plot 2: Contour Map ---
    if len(xv) > 3:  # Triangulation needs at least 3 valid points
        # Filled contours
        contourf = ax2.tricontourf(xv, yv, zv, levels=20, cmap=cmap_name)
        # Black contour lines on top for structure
        ax2.tricontour(xv, yv, zv, levels=15, colors='k', linewidths=0.4, alpha=0.7)
        
        fig.colorbar(contourf, ax=ax2, label=title)
        ax2.set_xscale('log')
        ax2.set_yscale('log')
        ax2.set_xlabel('Number Density')
        ax2.set_ylabel('N_NH3')
        ax2.set_title(f'{title} (Contour Map)')
        ax2.grid(True, which="both", ls="--", alpha=0.5)
    else:
        ax2.text(0.5, 0.5, 'Not enough valid points\nafter removing outliers', 
                 ha='center', va='center')

    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    plt.close()

# Define all the plots in a clean list format
plot_configs = [
    ('R_10_MAIN', 'R_10_MAIN', 'scatter_contour_r_10_main.png', 'viridis'),
    ('R_01_MAIN', 'R_01_MAIN', 'scatter_contour_r_01_main.png', 'plasma'),
    ('R_12_MAIN', 'R_12_MAIN', 'scatter_contour_r_12_main.png', 'cividis'),
    ('R_21_MAIN', 'R_21_MAIN', 'scatter_contour_r_21_main.png', 'magma')
]

print("Generating plots...")

# Loop through standard variables
for col, title, fname, cmap in plot_configs:
    z_data = remove_top_outliers(df[col])
    plot_scatter_and_contour(x, y, z_data, title, fname, cmap)
    print(f"Saved {fname}")

# Execute special ratio case
z_special = remove_top_outliers(df['A_01'] / df['A_10'])
plot_scatter_and_contour(x, y, z_special, 'A_01 / A_10', 'scatter_contour_a_01_over_a_10.png', 'inferno')
print("Saved scatter_contour_a_01_over_a_10.png")

print("All plots complete.")